// session.js — persists one JSON record per run session so `stop`/`status`
// resolve it from a fresh process (the E2E runner and agents invoke each op
// as a separate `node run.js` execution — nothing survives in memory between
// calls). Keyed by `session_id`; one file per session avoids concurrent-write
// races between unrelated sessions.
//
// Location: `evidence_dir` is not guaranteed to be present on `stop`/`status`
// (interfaces/run.md's stop/status examples carry only `session_id`), so the
// state dir is independent of it: AGENTFLOW_EXPO_STATE_DIR env override, else
// a fixed spot under the OS tmp dir.

import { mkdir, readFile, writeFile, unlink } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

export function resolveStateDir(env = process.env) {
  return env.AGENTFLOW_EXPO_STATE_DIR || join(tmpdir(), "agentflow-expo", "sessions");
}

function sessionPath(sessionId, stateDir) {
  if (!sessionId || typeof sessionId !== "string") {
    throw new TypeError("session_id must be a non-empty string");
  }
  // session ids are generated by this pack (see run.js#generateSessionId) and
  // never taken verbatim from an untrusted selector, but guard the join
  // anyway so a malformed id can't escape stateDir.
  const safe = sessionId.replaceAll(/[^a-zA-Z0-9._-]/g, "_");
  return join(stateDir, `${safe}.json`);
}

// record shape (see packs/expo/adapters/lib/README.md for the field-by-field
// contract):
//   {
//     session_id, workspace, target, profile, bundle_id,
//     agent_device_session, start_path: "reuse"|"build",
//     simulator_udid, metro: {pid,port,log,managed} | null,
//     entry_point, log_stream, evidence_dir, state,
//     created_at, updated_at
//   }
export async function saveSession(record, { stateDir = resolveStateDir() } = {}) {
  if (!record || !record.session_id) throw new TypeError("record.session_id is required");
  await mkdir(stateDir, { recursive: true });
  const now = new Date().toISOString();
  const existing = await loadSession(record.session_id, { stateDir }).catch(() => null);
  const full = {
    ...existing,
    ...record,
    created_at: existing?.created_at ?? record.created_at ?? now,
    updated_at: now,
  };
  await writeFile(sessionPath(record.session_id, stateDir), `${JSON.stringify(full, null, 2)}\n`);
  return full;
}

export async function loadSession(sessionId, { stateDir = resolveStateDir() } = {}) {
  const raw = await readFile(sessionPath(sessionId, stateDir), "utf8");
  return JSON.parse(raw);
}

export async function deleteSession(sessionId, { stateDir = resolveStateDir() } = {}) {
  await unlink(sessionPath(sessionId, stateDir)).catch((err) => {
    if (err.code !== "ENOENT") throw err;
  });
}
